# Generated by Django 4.0.6 on 2022-07-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnkenList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keiriShonin', models.BooleanField(blank=True, null=True)),
                ('statusCord', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('edabanGroup', models.IntegerField(blank=True, null=True)),
                ('shiharaiPattern', models.IntegerField(blank=True, null=True)),
                ('kanriNo', models.CharField(blank=True, max_length=30, null=True)),
                ('edaban', models.CharField(blank=True, max_length=30, null=True)),
                ('ankenMei', models.CharField(blank=True, max_length=30, null=True)),
                ('torihikisakiCode', models.IntegerField(blank=True, null=True)),
                ('torihikisakiMei', models.CharField(blank=True, max_length=30, null=True)),
                ('kanjokamoku', models.CharField(blank=True, max_length=30, null=True)),
                ('keikakuTanka', models.IntegerField(blank=True, null=True)),
                ('keikakuSuu', models.IntegerField(blank=True, null=True)),
                ('keikakuGokei', models.IntegerField(blank=True, null=True)),
                ('mitsumoriTanka', models.IntegerField(blank=True, null=True)),
                ('mitsumoriSuu', models.IntegerField(blank=True, null=True)),
                ('mitsumoriGokei', models.IntegerField(blank=True, null=True)),
                ('mtsumoriLink', models.URLField(blank=True, null=True)),
                ('wfNo', models.CharField(blank=True, max_length=30, null=True)),
                ('keiyakuKingaku', models.IntegerField(blank=True, null=True)),
                ('chumonTanka', models.IntegerField(blank=True, null=True)),
                ('chumonSuu', models.IntegerField(blank=True, null=True)),
                ('chumonGokei', models.IntegerField(blank=True, null=True)),
                ('chumonLink', models.URLField(blank=True, null=True)),
                ('nohinTanka', models.IntegerField(blank=True, null=True)),
                ('nohinSuu', models.IntegerField(blank=True, null=True)),
                ('nohinGokei', models.IntegerField(blank=True, null=True)),
                ('shiharaiTanka', models.IntegerField(blank=True, null=True)),
                ('konyuSuu', models.IntegerField(blank=True, null=True)),
                ('konyuGokei', models.IntegerField(blank=True, null=True)),
                ('seikyushoLink', models.URLField(blank=True, null=True)),
                ('keikaku_Jisseki', models.IntegerField(blank=True, null=True)),
                ('nohinKigen', models.DateTimeField(blank=True, null=True)),
                ('kenshuKigen', models.DateTimeField(blank=True, null=True)),
                ('shiharaiKigen', models.DateTimeField(blank=True, null=True)),
                ('kurikaeshiKigen', models.DateTimeField(blank=True, null=True)),
                ('ringishoLink', models.URLField(blank=True, null=True)),
                ('keiyakushoLink', models.URLField(blank=True, null=True)),
                ('konyuKaisha', models.CharField(blank=True, max_length=30, null=True)),
                ('dataKoshinbi', models.DateTimeField(blank=True, null=True)),
                ('saishuKoshinsha', models.CharField(blank=True, max_length=30, null=True)),
                ('shainNo', models.IntegerField(blank=True, null=True)),
                ('tantosha', models.CharField(blank=True, max_length=30, null=True)),
                ('comment', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'ankenListTable',
            },
        ),
    ]
