# Generated by Django 4.0.6 on 2022-09-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_add_allTable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnkenKanjokamoku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ankenKanjokamokuCode', models.IntegerField(blank=True, null=True)),
                ('ankenKanjokamoku', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'ankenKanjokamokuTable',
            },
        ),
    ]
