# Generated by Django 4.0.6 on 2022-10-07 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_add_kanjokamokuTable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankenlist',
            name='dataKoshinbi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
