# Generated by Django 4.0.6 on 2022-10-07 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_addDateDefault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankenlist',
            name='dataKoshinbi',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
